const state={severity:'all',status:'open',query:'',selected:null,ack:new Set()};
const $=s=>document.querySelector(s);const esc=s=>String(s).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]||c));
function devices(){return IoTShared.getFieldDevices()}
function severity(d){if(d.status==='offline'&&d.minutesSinceSeen>60)return 'critical';if(d.status==='offline')return 'high';return 'normal'}
function incidents(){return devices().filter(d=>d.status!=='online').map(d=>({d,sev:severity(d),ack:state.ack.has(d.id)}))}
function render(){const all=incidents();let rows=all.filter(x=>(state.severity==='all'||x.sev===state.severity)&&(state.status==='all'||(state.status==='ack')===x.ack)&&(`${x.d.name} ${x.d.id} ${x.d.zone} ${x.d.gateway||''}`.toLowerCase().includes(state.query)));$('#incident-list').innerHTML=rows.map(x=>`<tr><td><span class="sev-badge ${x.sev}">${x.sev==='critical'?'严重':x.sev==='high'?'高':'一般'}</span></td><td><b>${esc(x.d.status==='offline'?'通信超时':'遥测异常')}</b><div class="device-id">${x.d.offlineReason||'状态指标超出正常范围'}</div></td><td>${esc(x.d.name)}<div class="device-id">${esc(x.d.id)}</div></td><td>${esc(x.d.zone)}</td><td>${esc(x.d.minutesSinceSeen<=0?'刚刚':x.d.minutesSinceSeen+' 分钟前')}</td><td><span class="status-mini ${x.ack?'ack':''}">${x.ack?'已确认':'待确认'}</span></td><td><button class="action-mini" data-id="${esc(x.d.id)}">查看</button></td></tr>`).join('')||'<tr><td colspan="7" class="empty">当前筛选条件下没有事件</td></tr>';
$('#active-count').textContent=all.length;$('#critical-count').textContent=all.filter(x=>x.sev==='critical').length;$('#ack-count').textContent=all.filter(x=>x.ack).length;$('#nav-alert-count').textContent=all.length;$('#nav-device-count').textContent=devices().length;$('#queue-note').textContent=`${rows.length} / ${all.length} EVENTS`;
$('#incident-list').querySelectorAll('[data-id]').forEach(b=>b.addEventListener('click',()=>select(b.dataset.id)));}
function select(id){const x=incidents().find(x=>x.d.id===id);if(!x)return;state.selected=id;const d=x.d;$('#detail-title').textContent=d.name;$('#detail-sev').className=`sev-pill ${x.sev}`;$('#detail-sev').textContent=x.sev==='critical'?'P1 · 严重':x.sev==='high'?'P2 · 高':'P3 · 一般';$('#detail-body').innerHTML=`<div class="detail-grid"><div><small>设备 ID</small><strong>${esc(d.id)}</strong></div><div><small>当前状态</small><strong>${d.status==='offline'?'离线':'异常'}</strong></div><div><small>网关</small><strong>${esc(d.gateway||'Gateway-A01')}</strong></div><div><small>信号</small><strong>${d.rssi||'--'} dBm</strong></div><div><small>最近上报</small><strong>${d.minutesSinceSeen} 分钟前</strong></div><div><small>当前温度</small><strong>${d.temperature==null?'--':d.temperature+'°C'}</strong></div></div><div class="detail-section-box"><h3>ROOT CAUSE SIGNALS</h3><div class="cause-list"><div><i></i>${esc(d.offlineReason||'通信链路异常')}</div><div><i></i>网关侧连接稳定性需要进一步确认</div><div><i></i>建议对同网关设备进行关联分析</div></div></div><div class="detail-section-box"><h3>RECOMMENDED ACTION</h3><div class="recommend"><b>建议：</b>先确认 ${esc(d.gateway||'Gateway-A01')} 状态与 RSSI 分布；若同网关多设备同时异常，优先处理网关链路；若仅此设备异常，执行重新连接并观察恢复。</div><div class="detail-actions"><button class="action primary" id="ack-btn">${x.ack?'取消确认':'确认事件'}</button><a class="action" href="topology.html?device=${encodeURIComponent(d.id)}">查看拓扑</a><a class="action" href="maintenance.html?device=${encodeURIComponent(d.id)}">创建工单</a><a class="action" href="index.html#devices">设备档案</a></div></div>`;$('#ack-btn').addEventListener('click',()=>{x.ack?state.ack.delete(id):state.ack.add(id);render();select(id)});}
['all','critical','high','normal'].forEach(v=>document.querySelector(`[data-sev="${v}"]`).addEventListener('click',e=>{state.severity=v;document.querySelectorAll('[data-sev]').forEach(b=>b.classList.remove('active'));e.currentTarget.classList.add('active');render()}));$('#q').addEventListener('input',e=>{state.query=e.target.value.trim().toLowerCase();render()});$('#status').addEventListener('change',e=>{state.status=e.target.value;render()});document.querySelector('#clock').textContent=new Date().toLocaleTimeString('zh-CN');window.addEventListener('iot-model-change',render);render();