const statusText={online:'在线',offline:'离线',warning:'异常'};
const list=document.querySelector('#device-list'),search=document.querySelector('#search'),filter=document.querySelector('#status-filter');
const alerts=document.querySelector('#alerts'),map=document.querySelector('#device-map'),modal=document.querySelector('#detail-modal');
const reasonBox=document.querySelector('#offline-reason'),actionMessage=document.querySelector('#action-message'),historyPanel=document.querySelector('#history-panel');
let devices=IoTShared.getFieldDevices(),activeDeviceId=null;
function refreshModel(){devices=IoTShared.getFieldDevices();renderAll();if(activeDeviceId)openDetail(activeDeviceId)}
window.addEventListener('iot-model-change',refreshModel);
function formatLastSeen(minutes){if(minutes<=0)return '刚刚';if(minutes<60)return `${minutes} 分钟前`;return `${Math.floor(minutes/60)} 小时前`}
function renderSummary(){const total=devices.length,online=devices.filter(d=>d.status==='online').length,offline=devices.filter(d=>d.status==='offline').length,warning=devices.filter(d=>d.status==='warning').length,timeout=devices.filter(d=>d.status==='offline'&&d.minutesSinceSeen>10).length;document.querySelector('#total').textContent=total;document.querySelector('#online').textContent=online;document.querySelector('#offline').textContent=offline;document.querySelector('#warning').textContent=warning;document.querySelector('#timeout').textContent=timeout;document.querySelector('#online-rate').textContent=`${((online/total)*100).toFixed(1)}% 在线率`;document.querySelector('#alert-count').textContent=`${timeout} ACTIVE`;document.querySelector('#nav-alert-count').textContent=timeout;document.querySelector('#last-updated').textContent=new Date().toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit',second:'2-digit'});document.querySelector('#network-health').textContent=`${((online/total)*100).toFixed(1)}%`;document.querySelector('#health-bar').style.width=`${(online/total)*100}%`}
function renderMap(){map.querySelectorAll('.map-pin').forEach(x=>x.remove());devices.filter((_,i)=>i%13===0).forEach(d=>{const pin=document.createElement('button');pin.className=`map-pin ${d.status}`;pin.style.left=`${d.x}%`;pin.style.top=`${d.y}%`;pin.title=`${d.name} · ${statusText[d.status]}`;pin.setAttribute('aria-label',`查看 ${d.name}`);pin.addEventListener('click',()=>openDetail(d.id));map.appendChild(pin)})}
function renderAlerts(){const items=devices.filter(d=>d.status==='offline'&&d.minutesSinceSeen>10).slice(0,6);alerts.innerHTML=items.map(d=>`<div class="alert-item" data-id="${d.id}"><div class="alert-icon">!</div><div><strong>${d.name}</strong><span>${d.zone} · ${formatLastSeen(d.minutesSinceSeen)} · 超时未上报</span></div></div>`).join('')||'<div class="empty">暂无活动告警</div>';alerts.querySelectorAll('.alert-item').forEach(x=>x.addEventListener('click',()=>openDetail(x.dataset.id)))}
function signalHTML(d){if(!d.rssi)return '<span>--</span>';const level=Math.max(1,Math.min(5,Math.ceil((d.rssi+100)/10)));return `<div class="signal"><span class="signal-bars">${[1,2,3,4,5].map(i=>`<i style="height:${i*2+3}px;opacity:${i<=level?1:.2}"></i>`).join('')}</span><span>${d.rssi} dBm</span></div>`}
function batteryHTML(d){if(d.status==='offline')return '--';return `<div class="battery"><span class="battery-track"><i style="width:${d.battery}%"></i></span><span>${d.battery}%</span></div>`}
function renderTable(){const keyword=search.value.trim().toLowerCase(),selected=filter.value;const filtered=devices.filter(d=>`${d.name} ${d.id} ${d.zone}`.toLowerCase().includes(keyword)&&(selected==='all'||d.status===selected));list.innerHTML=filtered.slice(0,200).map(d=>`<tr data-id="${d.id}" tabindex="0"><td><div class="device-name">${d.name}</div><div class="device-id">${d.id} · ${d.zone}</div></td><td><span class="badge ${d.status}">${statusText[d.status]}</span></td><td>${signalHTML(d)}</td><td>${d.temperature===null?'--':`${d.temperature.toFixed(1)}°C`}</td><td>${batteryHTML(d)}</td><td>${formatLastSeen(d.minutesSinceSeen)}${d.status==='offline'&&d.minutesSinceSeen>10?' ⚠':''}</td><td class="row-action">›</td></tr>`).join('')||'<tr><td colspan="7" class="empty">没有找到匹配设备</td></tr>';document.querySelector('#shown-count').textContent=Math.min(filtered.length,200);list.querySelectorAll('tr[data-id]').forEach(row=>{row.addEventListener('click',()=>openDetail(row.dataset.id));row.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openDetail(row.dataset.id)}})})}
function renderTrend(d){document.querySelector('#trend-bars').innerHTML=(d.history||[]).map(x=>{const v=x.temperature===null?55:Math.max(25,Math.min(90,45+x.temperature));return `<div class="trend-bar" style="height:${v}%" title="${x.temperature===null?'无温度数据':`${x.temperature}°C`}"></div>`}).join('')}
function renderHistory(d){historyPanel.innerHTML=`<h3>最近历史数据</h3><div class="history-list">${(d.history||[]).map(x=>`<div class="history-row"><span>${x.time}</span><strong>${x.temperature===null?'--':`${x.temperature}°C`}</strong></div>`).join('')}</div><p class="history-note">当前为演示数据；真实版本可替换为数据库历史遥测。</p>`;historyPanel.classList.remove('hidden')}
function openDetail(id){const d=IoTShared.getDevice(id);if(!d)return;activeDeviceId=id;document.querySelector('#modal-name').textContent=d.name;document.querySelector('#modal-id').textContent=`${d.id} · ${d.zone}`;document.querySelector('#modal-status').textContent=statusText[d.status];document.querySelector('#modal-signal').textContent=d.rssi?`${d.rssi} dBm`:d.signal;document.querySelector('#modal-temperature').textContent=d.temperature===null?'--':`${d.temperature.toFixed(1)}°C`;document.querySelector('#modal-battery').textContent=`${d.battery}%`;const badge=document.querySelector('#modal-status-badge');badge.className=`status-badge ${d.status}`;badge.textContent=d.status.toUpperCase();if(d.status==='offline'){reasonBox.classList.remove('hidden');document.querySelector('#reason-main').textContent=d.offlineReason;document.querySelector('#reason-detail').textContent=`${d.offlineReasonDetail} 当前模拟电量：${d.battery}%。`}else reasonBox.classList.add('hidden');actionMessage.textContent='';historyPanel.classList.add('hidden');renderTrend(d);modal.classList.remove('hidden')}
function getActive(){return activeDeviceId?IoTShared.getDevice(activeDeviceId):null}
function reconnect(){const d=getActive();if(!d)return;if(d.status!=='offline'){actionMessage.textContent='设备当前不是离线状态，无需重新连接。';return}actionMessage.textContent='正在重新连接……';setTimeout(()=>{IoTShared.updateFieldDevice(d.id,{status:'online',signal:'一般',rssi:-66,minutesSinceSeen:0});actionMessage.textContent='✓ 重新连接成功，设备已恢复在线。';openDetail(d.id)},700)}
function restart(){const d=getActive();if(!d)return;actionMessage.textContent='正在发送重启指令……';setTimeout(()=>{const nextStatus=d.status==='offline'?'online':d.status;IoTShared.updateFieldDevice(d.id,{restartCount:(d.restartCount||0)+1,minutesSinceSeen:0,status:nextStatus,signal:nextStatus==='online'?'一般':d.signal,rssi:nextStatus==='online'?-66:d.rssi});actionMessage.textContent=`✓ 重启完成，第 ${(d.restartCount||0)+1} 次重启。`;openDetail(d.id)},700)}
function renderTelemetry(){const values=devices.filter(d=>d.temperature!==null).slice(0,30).map(d=>d.temperature);const avg=values.reduce((a,b)=>a+b,0)/values.length;document.querySelector('#avg-temp').textContent=`${avg.toFixed(1)}°C`;document.querySelector('#activity-count').textContent=(1120+(devices.filter(d=>d.status==='online').length%400)).toLocaleString();document.querySelector('#activity-bars').innerHTML=Array.from({length:14},(_,i)=>`<i style="height:${10+((i*17)%24)}px"></i>`).join('')}
function renderAll(){renderSummary();renderMap();renderAlerts();renderTable();renderTelemetry()}
document.querySelector('#close-modal').addEventListener('click',()=>{modal.classList.add('hidden');activeDeviceId=null});document.querySelector('#reconnect-btn').addEventListener('click',reconnect);document.querySelector('#restart-btn').addEventListener('click',restart);document.querySelector('#history-btn').addEventListener('click',()=>{const d=getActive();if(d)renderHistory(d)});modal.addEventListener('click',e=>{if(e.target===modal){modal.classList.add('hidden');activeDeviceId=null}});document.addEventListener('keydown',e=>{if(e.key==='Escape'){modal.classList.add('hidden');activeDeviceId=null}});search.addEventListener('input',renderTable);filter.addEventListener('change',renderTable);document.querySelector('#refresh-btn').addEventListener('click',renderAll);document.querySelector('#show-alerts').addEventListener('click',()=>{filter.value='offline';renderTable();document.querySelector('#devices').scrollIntoView({behavior:'smooth'})});renderAll();