const params=new URLSearchParams(location.search);const contextDevice=params.get('device');
const list=document.querySelector('#work-list');
const baseOrders=[['WO-260914-018','A-1032 通信恢复检查','A 区温室 · Gateway-A03','P1','处理中','A-1032'],['WO-260914-017','B-0718 温度异常排查','B 区冷库 · Gateway-B02','P2','待处理','B-0718'],['WO-260914-016','D-0321 泵站执行器巡检','D 区泵站 · Gateway-D01','P2','待处理','D-0321'],['WO-260914-015','E-0418 电表数据漂移','E 区配电房 · Gateway-E04','P3','已完成','E-0418'],['WO-260914-014','C-0788 传感器电池检查','C 区仓库 · Gateway-C02','P3','已完成','C-0788']];
const orders=JSON.parse(localStorage.getItem('iot-work-orders')||'null')||baseOrders;const states=['待处理','已分派','处理中','待验证','已完成'];
function render(){const rows=contextDevice?orders.filter(o=>o.join(' ').toLowerCase().includes(contextDevice.toLowerCase())):orders;list.innerHTML=rows.map((o,i)=>{const idx=states.indexOf(o[4]);return `<div class="work-row"><span class="work-id">${o[0]}</span><div><b>${o[1]}</b><span>${o[2]} · ${o[5]||'--'}</span></div><span class="priority ${o[3].toLowerCase()}">${o[3]}</span><span class="work-status ${o[4]==='已完成'?'done':''}">${o[4]}</span><button class="action-mini advance" data-i="${orders.indexOf(o)}" ${idx>=4?'disabled':''}>${idx>=4?'已关闭':'推进 →'}</button><a class="work-link" href="topology.html?device=${encodeURIComponent(o[5]||'')}">拓扑</a></div>`}).join('')||'<div class="empty">暂无与该设备匹配的工单</div>';
$('#open-count').textContent=orders.filter(o=>o[4]!=='已完成').length;$('#progress-count').textContent=orders.filter(o=>o[4]==='处理中').length;document.querySelectorAll('.advance').forEach(b=>b.addEventListener('click',()=>advance(+b.dataset.i)));}
function advance(i){const o=orders[i];const idx=states.indexOf(o[4]);if(idx<0||idx>=states.length-1)return;o[4]=states[idx+1];localStorage.setItem('iot-work-orders',JSON.stringify(orders));localStorage.setItem('iot-last-workorder-update',JSON.stringify({workOrder:o[0],deviceId:o[5],status:o[4],at:Date.now()}));render();}
function hydrateContext(){if(!contextDevice)return;const d=IoTShared.getFieldDevices().find(x=>x.id===contextDevice);const pending=JSON.parse(localStorage.getItem('iot-pending-workorder')||'null');const c=document.querySelector('#context-banner');if(!d&&!pending)return;c.classList.remove('hidden');const id=d?.id||pending?.deviceId||contextDevice;document.querySelector('#context-title').textContent=d?.name||pending?.deviceName||id;document.querySelector('#context-meta').textContent=`${id} · ${d?.zone||pending?.zone||'--'} · ${d?.gateway||pending?.gateway||'Gateway'} · ${d?.status||'待处置'}`;document.querySelector('#context-ai').href=`index.html?device=${encodeURIComponent(id)}#ai-section`;document.querySelector('#context-topology').href=`topology.html?device=${encodeURIComponent(id)}`;document.querySelector('#context-incident').href=`alerts.html?device=${encodeURIComponent(id)}`;}
document.querySelector('#new-order').addEventListener('click',()=>{const pending=JSON.parse(localStorage.getItem('iot-pending-workorder')||'null');const id=contextDevice||pending?.deviceId||'';const name=pending?.deviceName||(id?`设备 ${id}`:'现场巡检任务');const order=['WO-260914-'+String(19+orders.length).padStart(3,'0'),`${name} · AI 处置工单`,pending?.zone?`${pending.zone} · ${pending.gateway||'Gateway'}`:'自动创建 · 待分派',pending?.priority||'P2','待处理',id];orders.unshift(order);localStorage.setItem('iot-work-orders',JSON.stringify(orders));localStorage.removeItem('iot-pending-workorder');render();});
hydrateContext();render();