const devices=[
{id:'U-001',name:'客厅空调',room:'客厅',type:'aircon',icon:'❄',desc:'中央空调 · 最近连接正常',online:true,temp:24,mode:'制冷',fan:'自动',on:true},
{id:'U-002',name:'客厅主灯',room:'客厅',type:'light',icon:'☼',desc:'智能吸顶灯 · 亮度 80%',online:true,brightness:80,on:true},
{id:'U-003',name:'主卧空气净化器',room:'卧室',type:'air',icon:'◌',desc:'自动模式 · 空气优',online:true,aqi:28,on:true},
{id:'U-004',name:'主卧门锁',room:'卧室',type:'lock',icon:'⌑',desc:'指纹锁 · 3 小时前已锁',online:true,locked:true},
{id:'U-005',name:'厨房烟雾传感器',room:'厨房',type:'sensor',icon:'◈',desc:'环境监测 · 需要关注',online:true,alert:true,temp:31.8},
{id:'U-006',name:'厨房顶灯',room:'厨房',type:'light',icon:'☼',desc:'智能射灯 · 关闭',online:true,brightness:0,on:false},
{id:'U-007',name:'阳台水泵',room:'阳台',type:'pump',icon:'≈',desc:'灌溉设备 · 定时运行',online:true,on:false},
{id:'U-008',name:'阳台温湿度计',room:'阳台',type:'sensor',icon:'⌁',desc:'26.4°C · 湿度 61%',online:true,temp:26.4,humidity:61}
];
const grid=document.querySelector('#device-grid'),toast=document.querySelector('#toast'),modal=document.querySelector('#device-modal');let active=null,room='全部';
const icons={aircon:'❄',light:'☼',air:'◌',lock:'⌑',sensor:'◈',pump:'≈'};
function showToast(text){toast.textContent=text;toast.classList.add('show');clearTimeout(showToast.t);showToast.t=setTimeout(()=>toast.classList.remove('show'),2200)}
function deviceReading(d){if(d.type==='aircon')return `<strong>${d.temp}°</strong><span>设定温度</span>`;if(d.type==='light')return `<strong>${d.brightness}%</strong><span>亮度</span>`;if(d.type==='air')return `<strong>${d.aqi}</strong><span>AQI</span>`;if(d.type==='lock')return `<strong>${d.locked?'已锁':'已开'}</strong><span>门锁状态</span>`;if(d.type==='sensor')return `<strong>${d.temp??'--'}°</strong><span>${d.humidity?`湿度 ${d.humidity}%`:'温度'}</span>`;if(d.type==='pump')return `<strong>${d.on?'运行':'待机'}</strong><span>工作状态</span>`;return `<strong>--</strong><span>状态</span>`}
function render(){const items=devices.filter(d=>room==='全部'||d.room===room);grid.innerHTML=items.map(d=>`<article class="device-card" data-id="${d.id}"><div class="device-head"><div class="device-icon">${icons[d.type]||d.icon}</div><span class="device-state ${d.alert?'attention-state':''}"><i></i>${d.alert?'需要关注':'在线'}</span></div><h3>${d.name}</h3><p>${d.desc}</p><div class="device-reading">${deviceReading(d)}</div><div class="device-actions">${d.type==='light'?`<button class="mini-control ${d.on?'active':''}" data-action="toggle">${d.on?'◉':'○'}</button>`:d.type==='lock'?`<button class="mini-control ${d.locked?'active':''}" data-action="lock">${d.locked?'▣':'□'}</button>`:d.type==='aircon'?`<button class="mini-control ${d.on?'active':''}" data-action="toggle">${d.on?'❄':'○'}</button>`:d.type==='pump'?`<button class="mini-control ${d.on?'active':''}" data-action="toggle">${d.on?'Ⅱ':'▶'}</button>`:''}<button class="mini-control" data-action="open">›</button></div></article>`).join('');grid.querySelectorAll('.device-card').forEach(card=>{card.addEventListener('click',e=>{const a=e.target.closest('[data-action]');const d=devices.find(x=>x.id===card.dataset.id);if(!a||a.dataset.action==='open'){openDevice(d);return}e.stopPropagation();handleQuick(d,a.dataset.action)})});document.querySelector('#nav-alerts').textContent=devices.filter(d=>d.alert).length}
function handleQuick(d,action){if(action==='toggle'){d.on=!d.on;if(d.type==='light'&&!d.on)d.brightness=0;if(d.type==='light'&&d.on&&d.brightness===0)d.brightness=80;showToast(`${d.name} 已${d.on?'开启':'关闭'}`)}else if(action==='lock'){d.locked=!d.locked;showToast(`${d.name} 已${d.locked?'锁定':'解锁'}`)}render();if(active?.id===d.id)openDevice(d)}
function openDevice(d){active=d;document.querySelector('#modal-icon').textContent=icons[d.type]||d.icon;document.querySelector('#modal-room').textContent=d.room;document.querySelector('#modal-name').textContent=d.name;document.querySelector('#modal-desc').textContent=d.desc;document.querySelector('#modal-state').textContent=d.online?'在线':'离线';document.querySelector('#modal-last').textContent=d.online?'刚刚更新':'暂时无法连接';document.querySelector('#control-area').innerHTML=controlsFor(d);modal.classList.remove('hidden');bindControls(d)}
function controlsFor(d){if(d.type==='aircon')return `<div class="control-title">AIR CONDITIONER</div><div class="toggle"><span>电源</span><button class="power ${d.on?'on':''}" data-cmd="power"><i></i></button></div><div class="temp-box" style="margin-top:12px"><div><small>目标温度</small><strong>${d.temp}°C</strong></div><div class="temp-step"><button data-cmd="minus">−</button><button data-cmd="plus">＋</button></div></div><div class="select-row"><button class="${d.mode==='制冷'?'active':''}" data-cmd="cool">制冷</button><button class="${d.mode==='除湿'?'active':''}" data-cmd="dry">除湿</button><button class="${d.fan==='自动'?'active':''}" data-cmd="auto">自动风</button><button class="${d.fan==='静音'?'active':''}" data-cmd="quiet">静音</button></div>`;if(d.type==='light')return `<div class="control-title">LIGHTING</div><div class="toggle"><span>电源</span><button class="power ${d.on?'on':''}" data-cmd="power"><i></i></button></div><div class="range-row"><span>亮度</span><input id="brightness-range" type="range" min="0" max="100" value="${d.brightness||0}"/><strong id="brightness-value">${d.brightness||0}%</strong></div>`;if(d.type==='lock')return `<div class="control-title">SMART LOCK</div><div class="temp-box"><div><small>当前状态</small><strong>${d.locked?'已锁定':'已解锁'}</strong></div><div class="lock-actions"><button data-cmd="lock">${d.locked?'解锁':'上锁'}</button><button class="secondary" data-cmd="history">记录</button></div></div>`;if(d.type==='air')return `<div class="control-title">AIR PURIFIER</div><div class="toggle"><span>自动模式</span><button class="power ${d.on?'on':''}" data-cmd="power"><i></i></button></div><div class="temp-box" style="margin-top:12px"><div><small>空气质量</small><strong>AQI ${d.aqi}</strong></div><span style="color:#42ae7f;font-size:11px">优</span></div>`;if(d.type==='pump')return `<div class="control-title">WATER PUMP</div><div class="toggle"><span>水泵开关</span><button class="power ${d.on?'on':''}" data-cmd="power"><i></i></button></div><div class="select-row"><button class="active" data-cmd="schedule">定时灌溉</button><button data-cmd="manual">手动运行</button></div>`;return `<div class="control-title">ENVIRONMENT</div><div class="temp-box"><div><small>当前温度</small><strong>${d.temp||'--'}°C</strong></div><span>${d.humidity?`湿度 ${d.humidity}%`:'正常'}</span></div>`}
function bindControls(d){document.querySelectorAll('[data-cmd]').forEach(btn=>btn.addEventListener('click',()=>{const c=btn.dataset.cmd;if(c==='power'){d.on=!d.on;showToast(`${d.name} 已${d.on?'开启':'关闭'}`)}else if(c==='plus'){d.temp=Math.min(30,d.temp+1)}else if(c==='minus'){d.temp=Math.max(16,d.temp-1)}else if(c==='cool'){d.mode='制冷'}else if(c==='dry'){d.mode='除湿'}else if(c==='auto'){d.fan='自动'}else if(c==='quiet'){d.fan='静音'}else if(c==='lock'){d.locked=!d.locked;showToast(`${d.name} 已${d.locked?'锁定':'解锁'}`)}else if(c==='history'){showToast('门锁记录将在真实版本接入后显示')}else if(c==='schedule'){showToast('已切换到定时灌溉')}else if(c==='manual'){d.on=true;showToast('水泵已开始手动运行')}openDevice(d);render()});const range=document.querySelector('#brightness-range');if(range)range.addEventListener('input',()=>{d.brightness=Number(range.value);d.on=d.brightness>0;document.querySelector('#brightness-value').textContent=`${d.brightness}%`;render()})}
document.querySelector('#modal-close').addEventListener('click',()=>{modal.classList.add('hidden');active=null});modal.addEventListener('click',e=>{if(e.target===modal){modal.classList.add('hidden');active=null}});document.querySelectorAll('.room-card').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.room-card').forEach(x=>x.classList.remove('active'));btn.classList.add('active');room=btn.dataset.room;render()}));document.querySelectorAll('.scene-card').forEach(btn=>btn.addEventListener('click',()=>{const scene=btn.dataset.scene;if(scene==='回家'){devices.filter(d=>d.type==='light').forEach(d=>{d.on=true;d.brightness=d.brightness||80});devices.find(d=>d.type==='aircon').on=true}if(scene==='离家'){devices.filter(d=>d.type==='light'||d.type==='aircon').forEach(d=>d.on=false);devices.find(d=>d.type==='lock').locked=true}if(scene==='晚安'){devices.filter(d=>d.type==='light').forEach(d=>d.on=false);devices.find(d=>d.type==='lock').locked=true;devices.find(d=>d.type==='aircon').on=true}showToast(`“${scene}”场景已执行`);render()}));document.querySelector('#add-device').addEventListener('click',()=>showToast('添加设备功能已预留，真实版本可接入扫码 / BLE / Wi-Fi 配网'));document.querySelector('#energy-detail').addEventListener('click',()=>showToast('今日 18.6 kWh · 空调占比最高'));document.querySelectorAll('.attention').forEach(x=>x.addEventListener('click',()=>showToast('已打开提醒：请确认厨房灶台状态')));render();